export const GET_BOARD_REQUEST = 'GET_BOARD_REQUEST';
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS';
export const GET_BOARD_FAILURE = 'GET_BOARD_FAILURE';
export const GET_BOARD = [
    GET_BOARD_REQUEST,
    GET_BOARD_SUCCESS,
    GET_BOARD_FAILURE
];

export const POST_NEW_USER_REQUEST = 'POST_NEW_USER_REQUEST';
export const POST_NEW_USER_SUCCESS = 'POST_NEW_USER_SUCCESS';
export const POST_NEW_USER_FAILURE = 'POST_NEW_USER_FAILURE';
export const POST_NEW_USER = [
    POST_NEW_USER_REQUEST,
    POST_NEW_USER_SUCCESS,
    POST_NEW_USER_FAILURE
];

export const POST_ARTISTS_REQUEST = 'POST_ARTISTS_REQUEST';
export const POST_ARTISTS_SUCCESS = 'POST_ARTISTS_SUCCESS';
export const POST_ARTISTS_FAILURE = 'POST_ARTISTS_FAILURE';
export const POST_ARTISTS = [
    POST_ARTISTS_REQUEST,
    POST_ARTISTS_SUCCESS,
    POST_ARTISTS_FAILURE
];

