export const POST_NEW_USER_REQUEST = 'POST_NEW_USER_REQUEST';
export const POST_NEW_USER_SUCCESS = 'POST_NEW_USER_SUCCESS';
export const POST_NEW_USER_FAILURE = 'POST_NEW_USER_FAILURE';
export const POST_NEW_USER = [
    POST_NEW_USER_REQUEST,
    POST_NEW_USER_SUCCESS,
    POST_NEW_USER_FAILURE
];

